server:
  port: 8080

spring:
  application:
    name: api-gateway


  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: inkasalud-super-secret-key-2026-123456

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/clientes/**

        - id: personal-service
          uri: lb://personal-service
          predicates:
            - Path=/farmaceuticos/**

        - id: catalogo-service
          uri: lb://catalogo-service
          predicates:
            - Path=/productos/**,/categorias/**

        - id: ventas-service
          uri: lb://ventas-service
          predicates:
            - Path=/ventas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.security.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"